/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./../src/views/components/dialog/index.vue')['default']
    Home: typeof import('./../src/views/home/index.vue')['default']
    Login: typeof import('./../src/views/login/index.vue')['default']
    Menu: typeof import('./../src/views/menu/index.vue')['default']
    MenuView: typeof import('./../src/views/menu/menuView.vue')['default']
    NotFound: typeof import('./../src/views/notFound.vue')['default']
    NoticeSlide: typeof import('./../src/components/NoticeSlide/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    XtDialog: typeof import('./../src/components/XtDialog/index.vue')['default']
  }
}
