/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ai: typeof import('./../src/views/components/ai/index.vue')['default']
    Audit: typeof import('./../src/views/components/Audit/index.vue')['default']
    copy: typeof import('./../src/views/components/dialog/index copy.vue')['default']
    CreateSupplier: typeof import('./../src/views/components/SupplierManagement/CreateSupplier/index.vue')['default']
    Dialog: typeof import('./../src/views/components/dialog/index.vue')['default']
    Echarts: typeof import('./../src/views/components/echarts/index.vue')['default']
    Home: typeof import('./../src/views/home/index.vue')['default']
    IssueInventory: typeof import('./../src/views/components/IssueInventory/index.vue')['default']
    Login: typeof import('./../src/views/login/index.vue')['default']
    MaterialManagement: typeof import('./../src/views/components/MaterialManagement/index.vue')['default']
    NotFound: typeof import('./../src/views/notFound.vue')['default']
    NoticeSlide: typeof import('./../src/components/NoticeSlide/index.vue')['default']
    OrdersList: typeof import('./../src/views/components/OrdersList/index.vue')['default']
    Outbound: typeof import('./../src/views/components/Outbound/index.vue')['default']
    Payment: typeof import('./../src/views/components/Payment/index.vue')['default']
    PlanPurchase: typeof import('./../src/views/components/PlanPurchase/index.vue')['default']
    Procure: typeof import('./../src/views/components/Procure/index.vue')['default']
    Records: typeof import('./../src/views/components/Records/index.vue')['default']
    Reload: typeof import('./../src/views/reload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SupplierList: typeof import('./../src/views/components/SupplierManagement/SupplierList/index.vue')['default']
    SupplierManagement: typeof import('./../src/views/components/SupplierManagement/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    Switch: typeof import('./../src/views/components/switch/index.vue')['default']
    WarehouseManagement: typeof import('./../src/views/components/WarehouseManagement/index.vue')['default']
    WarehouseStock: typeof import('./../src/views/components/WarehouseStock/index.vue')['default']
    XtDialog: typeof import('./../src/components/XtDialog/index.vue')['default']
  }
}
